version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - setup_remote_docker
      - run: ssh remote-docker && echo "blahblahblah" > test && cat test && pwd